### ISSUE TITLE
Description of Realms.

### ISSUE THREAD

**Issue by trusktr** [caridy/proposal-realms#1]
Besides having the spec here, it'd be nice to link to (or write directly) what a Realm is, so that the spec makes more sense to those not yet familiar with what Realms are.

I myself am not even sure what to Google, as "realm" is a fairly generic word. Even "programming realm" doesn't help (or Google can't guess what I'm looking for).

**Comment by trusktr** [comment]
Closing, PR https://github.com/caridy/proposal-realms/pull/2

**Comment by caridy** [comment]
@trusktr thanks for the PR. This is definitely work in progress, I plan to add more details after done with the knowledge transfer from @dherman.
