### ISSUE TITLE
How to get reference to current global realm

### ISSUE THREAD

**Issue by isiahmeadows** [caridy/proposal-realms#15]
This would be *very* useful for certain security applications, to restrict or modify a function's behavior (e.g. like what weak references already require) if it's called from a different realm. Something like `get Realm.current` would be perfect for this application.

```js
const myRealm = Realm.current
const theirRealm = new Realm()

myRealm !== theirRealm.eval("Realm.current")
theirRealm === theirRealm.eval("Realm.current")
```

**Comment by isiahmeadows** [comment]
Or, probably better, this should get a backing reference linked to the realm itself instead. That way the realm remains independent of the code run inside it.

```js
const reference = Realm.this
const realm = new Realm()

reference !== theirRealm.eval("Realm.this")
realm.this === theirRealm.eval("Realm.this")
```

**Comment by erights** [comment]
What is a "backing reference"?

**Comment by caridy** [comment]
@isiahmeadows can you provide more details on why "certain security applications" do need this? So far we haven't encounter a scenario where we want to expose the realm power object directly in user-land.

**Comment by isiahmeadows** [comment]
@caridy I was working on a ponyfill for the weak reference proposal, and I found I couldn't lock it down to the current realm. Although I will admit I was getting a little ahead of myself in overstating the problem.
