### ISSUE TITLE
Does this proposal subsume the old one?

### ISSUE THREAD

**Issue by erights** [caridy/proposal-realms#3]
Does this proposal subsume the Realm API proposal at https://gist.github.com/dherman/7568885 ?

**Comment by caridy** [comment]
@erights we are still in the first phase here, for now, I'm only bringing the noncontroversial parts of the initial proposal, I need to have few discussions with @dherman about this (hopefully next week), so I can start spec'ing the rest, and I'm sure he has changed his mind about few things already :)
