### ISSUE TITLE
[shim] evaluate whether or not strict mode have to be enforced

### ISSUE THREAD

**Issue by caridy** [caridy/proposal-realms#32]

**Comment by erights** [comment]
The spec, and platforms built to conform, should not enforce strict mode by default. However, there should be some straightforward and reliable way to use the Realm api to enforce strict-only. In particular, many of the anticipated uses for frozen realms will want to enforce strict-only.

For the shim, it is not an option to allow sloppy code. Sloppy code in the shim can use this-coercion to obtain access to the actual global object, thereby penetrating the shim's emulation of the spec and reaching through to the hidden implementation. So the shim has a choice of failing to implement the spec in one of two ways:

  * It can fail to provide sloppy mode
  * It can fail to hide the real implementation global, that pierces the illusion of providing an emulated global instead.

Clearly, the lesser evil is to lose sloppy support in the shim.

**Comment by caridy** [comment]
Specifically, @erights is talking about this:

```js
function foo() {
    return this;
}
foo.call(null); // yield the confinedWindow reference (which is the realm global that we are shadowing in the iframe)
```
