### ISSUE TITLE
HTML misrenders

### ISSUE THREAD

**Issue by erights** [caridy/proposal-realms#37]
HTML at https://rawgit.com/caridy/proposal-realms/master/index.html misrenders for me as shown in the attachment.

![screen shot 2016-12-21 at 5 31 18 am](https://cloud.githubusercontent.com/assets/273868/21391115/111671aa-c73f-11e6-9a33-425ff90834ce.png)

**Comment by ljharb** [comment]
It needs to use the --css and --js options from ecmarkup instead of hot linking them.
